print("Que sale de la cruza entre un mono y un pato?", end="")
input()
print("Un monopatin!")
print()
print("Por que vuelan los pajaros pa\'l sur?", end="")
input()
print("Porque caminando tardarian muchisimo!")
print()
print("En que se parecen una familia, un bombero y un barco?", end="")
input()
print("No se... En que se parecen?", end="")
input()
print("En que el bombero y el barco tienen casco.")
print("Y la familia?", end="")
print(" - Bien, gracias.")